sprint-1/step-2
ha308ing/stellar-burgers pull request #2
Opened 2024-05-23 10:45 UTC by ha308ing

# Спринт 1. Шаг 2.

## Задачи

- переписать компоненты на классах в функциональные
- получать данные ингридиентов через api
- модальные окна
  - информация об ингредиенте (клик по ингридиенту)
  - информация о заказе (клик по кнопке "Оформить заказ")

## Демо

[![2024-05-23-12-12-13.gif](https://i.postimg.cc/sxPYwpsk/2024-05-23-12-12-13.gif)](https://postimg.cc/y3d3N3Jj)

## Лог

- sprint-1/step-1: #1
- **feat: switch to functional components**
- **feat: modals**
- **feat: get ingredients data from api**
- **chore: update readme**

2024-05-24 07:57 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Есть модальные окна;
- Данные получают с сервера;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил замечания в коде;

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +  const [orderState] = useState(order);
**Надо исправить:**

На ранних этапах лучше просто использовать переменную `order`, а не делать из неё отдельный стейт)) А уже потом вы познакомитесь с редакс, и будете контролировать состояние заказа через него.

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +  };
**Можно лучше:**

в дальнейшем добавятся ещё запросы к бэкенду и лучше вынести описание этих запросов в функции

Например:

```js
function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(проверка ответа)
}
```

и разместить их в отдельном файле `utils/burger-api.js`, а не описывать запросы в самом компоненте

```jsx
// использование
getIngredients()
  .then(setState)
  .catch(...)
  .finally()
```
или через `try_catch`

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +      if (!response.ok) throw Error();
**Можно лучше:**

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkResponse = res => {
  return res.ok ? res.json() : res.json().then(err => Promise.reject(err));
};
```

`fetch(someUrl).then(checkResponse)`

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredient/burger-ingredient.jsx
> +}) => (
**Надо исправить:**

лучше передавать в пропсы весь объект ингредиента, а не его поля.

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients-group/burger-ingredients-group.jsx
> +          <BurgerIngredientWithModal key={ingredient._id} {...ingredient} />
**Надо исправить:**

лучше передавать в пропсы весь объект ингредиента, а не его поля.

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/modal-portal/modal-overlay/modal-overlay.jsx
> +  closeModalHandler: PropTypes.func,
**Надо исправить:**

тут `.isRequired`))

2024-05-24 07:57 UTC, ArslanMustafin commented on src/components/modal-portal/modal-portal.jsx
> +  }, [keyHandler, closeModalHandler]);
**Надо исправить:**

Такие условия всегда лучше писать от противного:

```js
if(!closeModalHandler) return 

document.addEventListener("keyup", keyHandler);

return () => {
  document.removeEventListener("keyup", keyHandler);
};
```

2024-05-24 07:57 UTC, ArslanMustafin commented on src/utils/prop-types/ingredient-with-qty-shape.js
> +};
**Надо исправить:**

у всех полей нужно проставить `.isRequired`

2024-05-25 10:57 UTC, ha308ing commented on src/components/app/app.jsx
> +  const [orderState] = useState(order);
[16fc792](https://github.com/ha308ing/stellar-burgers/pull/2/commits/16fc792a98a1e2c43ba19608bf48f4f887ddf4c7)

2024-05-25 10:58 UTC, ha308ing commented on src/components/app/app.jsx
> +  };
[b3051b2](https://github.com/ha308ing/stellar-burgers/pull/2/commits/b3051b2fbd43562a029279700e73dd73a151c8e3)

2024-05-25 10:59 UTC, ha308ing commented on src/components/burger-ingredients/burger-ingredient/burger-ingredient.jsx
> +}) => (
[c7fddc9](https://github.com/ha308ing/stellar-burgers/pull/2/commits/c7fddc9c15bd1ad927484fe7a04d64c6303e37fd)

2024-05-25 11:00 UTC, ha308ing commented on src/components/modal-portal/modal-portal.jsx
> +  }, [keyHandler, closeModalHandler]);
[45222a1](https://github.com/ha308ing/stellar-burgers/pull/2/commits/45222a1623d33157edd8608f23128c085f019787)

2024-05-25 11:00 UTC, ha308ing commented on src/utils/prop-types/ingredient-with-qty-shape.js
> +};
[5aa5632](https://github.com/ha308ing/stellar-burgers/pull/2/commits/5aa563210fe9ed248af1264ac63449387443a6b2)

2024-05-25 11:33 UTC, ha308ing commented on src/components/modal-portal/modal-overlay/modal-overlay.jsx
> +  closeModalHandler: PropTypes.func,
Добрый день! Спасибо за комментарии! 👍

Есть модьные окна, которые нельзя закрывать (`ModalLoading`, `ModalConnectError`), поэтому `closeModalHandler` может быть `null`.

[e2c40de](https://github.com/ha308ing/stellar-burgers/pull/2/commits/e2c40de46d685a94de87de2603a41db620fa5e33)

2024-05-25 15:32 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2024-05-25 15:32 UTC, ArslanMustafin commented on src/utils/burgers-api-service.js
> +  };
**Можно лучше:**

не очень хорошая практика смешивать сервисы и бизнес логику. 
Сервис у вас должен получать от сервера ответ, и отдавать его (возможно как-то преобразовывая), он не должен знать что дальше будет происходить с данными)) Поэтому лучше все манипуляции с данными делать в самом компоненте (или где-то ещё, но не в сервисе). Так код будет намного более переиспользуемым и гибким.

2024-05-25 15:32 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredient/burger-ingredient.jsx
> +  ingredient: PropTypes.shape(ingredientWithQtyType).isRequired,
**Можно лучше:**

у вас ведь есть `ingredientWithQtyShape`) можно использовать его

2024-05-25 15:32 UTC, ArslanMustafin commented on src/components/ingredient-details/ingredient-details-modal.jsx
> +  ingredient: PropTypes.shape(ingredientWithQtyType).isRequired,
**Можно лучше:**

можно переиспользовать ingredientWithQtyShape

2024-06-04 20:22 UTC, merged